dist: trusty

language: php

php:
  - 7.1

matrix:
  fast_finish: true

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction

after_success:
  - travis_retry php vendor/bin/coveralls -v

script:
  - mkdir -p build/logs
  - phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml

cache:
  directories:
    - "$HOME/.composer/cache/files"
